---
scratchdir: "/gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/"

genome: "/gpfs/gibbs/project/dunn/lem79/CyaneaPop...
Gen/Mapping/IsoSeq/Filtered/Cyanea_sp_transcripts.strict.fasta"

prior_mutation_rate: 0.001
min_qual: 20
min_depth: 2
max_depth: 99
min_ind: 1

sample:
 CyaneaCapillataLEM1:
  reads:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM1_098_095_S38_L003_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM1_098_095_S38_L003_R2_001.fastq.gz
  CyaneaCapillataLEM2:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM2_181_012_S39_L003_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM2_181_012_S39_L003_R2_001.fastq.gz
  CyaneaCapillataLEM6:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM6_169_024_S40_L003_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LEM6_169_024_S40_L003_R2_001.fastq.gz
  CyaneaCapillataLEM137:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LM137_171_022_S3_L007_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LM137_171_022_S3_L007_R2_001.fastq.gz
  CyaneaFulvaLMD324:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LMD324_136_057_S21_L008_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LMD324_136_057_S21_L008_R2_001.fastq.gz
  CyaneaFulvaLMD524:
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LMD524_148_045_S22_L008_R1_001.fastq.gz
   - /gpfs/gibbs/project/dunn/lem79/CyaneaPopGen/Mapping/reads/LMD524_148_045_S22_L008_R2_001.fastq.gz
